#!/bin/sh

opkg update
opkg install apache

# remove unnecessary files after install
rm /tmp/opkg-lists/*


# create subdirs for additional configuration and site defs
# all *.conf files are included into the main config
# this will be the mechanism to add custom applications
# to this base image
mkdir /etc/apache/conf/
mkdir /etc/apache/sites/
printf "Include /etc/apache/conf/*.conf\n" >> /etc/apache/httpd.conf
printf "Include /etc/apache/sites/*.conf\n\n" >> /etc/apache/httpd.conf
